SIM=icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/parallel_perceptron_tb.v
TOPLEVEL = parallel_perceptron_tb
MODULE = parallel_perceptron_test

include $(shell cocotb-config --makefiles)/Makefile.sim
