SIM=icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/moving_average_tb.v
TOPLEVEL = moving_average_tb
MODULE = moving_average_test 

include $(shell cocotb-config --makefiles)/Makefile.sim
